### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "vali@mail.ru",
  "password": "5555"
}


### Registration
POST localhost:8080/api/v1/auth/register
Content-Type:  application/json

{
  "name": "Alish",
  "surname": "Aliyev",
  "email": "sarvar@gmail.com",
  "phone": "333",
  "password": "5555"
}