### create tag
POST localhost:8080/api/v1/tag/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODMwMTA3MjQsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwOTcxMjQsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.yPTg3mCjaJP5MPBKmREZibbqXkzoCHC3OYwZOMHNkbaRXR0vCopHvB9ugcZ8SEQq9sl1cy4mE_8ljL4Y9Ectpw
Content-Type:  application/json

{
  "name": "dsdsddsddd"

}

### update tag
PUT localhost:8080/api/v1/tag/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4OTM1MDIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5Nzk5MDIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CO_WZGhTclnIKew2MZjQ43H-6xNqIL3asLsfsRT1cXpNbpFAmITqDF7NJwT9LHn_11ey8qBUMm3yT1RG-aesQg
Content-Type:  application/json

{

  "name": "journalist"

}

### delete tag
DELETE localhost:8080/api/v1/tag/9
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE4OTM1MDIsImlkIjozLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5Nzk5MDIsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.CO_WZGhTclnIKew2MZjQ43H-6xNqIL3asLsfsRT1cXpNbpFAmITqDF7NJwT9LHn_11ey8qBUMm3yT1RG-aesQg
Content-Type:  application/json
